### ISSUE TITLE
Merge this into the OpenCV?

### ISSUE THREAD

**Issue by liquidmetal** [vrishe/AnnexCV#1]
It seems like this could be very useful in the OpenCV library. Have you considered merging this with their codebase?

**Comment by liquidmetal** [comment]
Haven't heard back - I can help get this merged into OpenCV.

**Comment by vrishe** [comment]
Greetings! If you find it useful, sure then. Please, let me know if you need something from me.

**Comment by vrishe** [comment]
This code is pretty old, so I did a little revision to figure out, what's going on there. Actually, there is a module initialization part that confuses me a little: [https://github.com/vrishe/AnnexCV/blob/master/AnnexCV/src/init_module.cpp](url). 
Please, pay attention to how algorithm object setters are being provided in there. I think I did something awful in there =).

**Comment by liquidmetal** [comment]
Excellent! Right now I'm trying to get this to run in my own codebase. Once I understand what's going on, I'll attempt getting this merged into OpenCV!
